name: "Lint 🧹"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint 🧹"
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run Swiftformat
        run: swiftformat . --lint --config ".swiftformat"
