name: "Lint 🧹"

on:
  pull_request:
    types:
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Lint 🧹"
    if: github.event.pull_request.draft == false
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run Swiftformat
        run: swiftformat . --lint --config ".swiftformat"
